version: '3.8'
services:
  lego:
    image: goacme/lego
    command: --dns godaddy -d domain.test -d *.domain.test --email your-email run
    environment:
      - CLOUDFLARE_EMAIL
    volumes:
      - ./letsencrypt:/.lego
    restart: always
