version: '3.8'
services:
  lego:
    image: goacme/lego
    entrypoint: watch -n 604800
    command: lego --dns cloudflare -d domain.test -d *.domain.test --email your-email -a run
    environment:
      - CLOUDFLARE_EMAIL=
      - CLOUDFLARE_API_KEY=
    volumes:
      - ./letsencrypt:/.lego
